set_load 0.3614 [all_outputs]
set_driving_cell -lib_cell SAEDHVT14_BUF_1 [all_inputs]
set_clock_uncertainty [expr 0.01 * $clock_period] [get_clocks clk_i]

#set_dont_use [get_lib_cells */*_1]
#set_dont_use [get_lib_cells */*_2]
#set_dont_use [get_lib_cells */*_0P5*]
#set_dont_use [get_lib_cells */*_0P75*]
#set_dont_use [get_lib_cells */*_1P5]

#set_load 0.16  [get_ports core_sleep_o]
#set_load 0.16  [get_ports data_addr_o[*]]
#set_load 0.16  [get_ports data_wdata_o[*]]
#set_load 0.16  [get_ports instr_addr_o[*]]
#set_load 0.16  [get_ports {data_be_o[0] data_be_o[1] data_be_o[2] data_be_o[3]}]

#set_load 0.16  [get_ports {irq_id_o[0] irq_id_o[2]}]
#set_load 0.16  [get_ports core_i/id_stage_i/register_file_i/*]
#set_load 0.16  [get_nets core_i/if_stage_i/prefetch_buffer_i/prefetch_controller_i/*]
#set_load 0.16  [get_nets core_i/id_stage_i/decoder_i/*]
#set_load 0.16  [get_nets core_i/id_stage_i/register_file_i/*]
#set_load 0.16  [get_nets core_i/id_stage_i/controller_i/*]
#set_load 0.16  [get_nets core_i/ex_stage_i/alu_i/*]
#set_load 0.16  [get_nets irq_id_o[1]]
